Repository spencercjh/my-blog, pull requests merged in 2025-09, with the labels that each got.

#27 feat: introduce a new blog about SSH shell session
  blog/2025-09-12-ssh-session-env/assets/bash-login-work.png
  blog/2025-09-12-ssh-session-env/assets/complete-graph.png
  blog/2025-09-12-ssh-session-env/assets/exp-result-1.png
  blog/2025-09-12-ssh-session-env/assets/exp-result-analyse-1.png
  blog/2025-09-12-ssh-session-env/assets/home-profile-work.png
  blog/2025-09-12-ssh-session-env/assets/non-login-non-interactive-session-analyse-1.png
  blog/2025-09-12-ssh-session-env/assets/normal-bash-process.png
  blog/2025-09-12-ssh-session-env/assets/normal-ssh-strace.png
  blog/2025-09-12-ssh-session-env/assets/warpify-bash-process.png
  blog/2025-09-12-ssh-session-env/assets/warpify-bash-rcfile.png
  blog/2025-09-12-ssh-session-env/assets/warpify-ssh-session.png
  blog/2025-09-12-ssh-session-env/complete-graph.dot
  blog/2025-09-12-ssh-session-env/ssh-session-env.mdx
  blog/tags.yml
Labels: Review effort 2/5

#28 fix(blog): fix typos; add more postscript
  blog/2025-09-12-ssh-session-env/ssh-session-env.mdx
Labels: Review effort 2/5

#29 fix typo
  blog/2025-05-09-bcm-engine/1-open-source-project-selection.mdx
  blog/2025-05-09-bcm-engine/2-internal-adaption.mdx
  blog/2025-05-09-bcm-engine/3-bugfix.mdx
Labels: Review effort 1/5

#30 feat(blog): introduce a new blog about `kubectl exec`
  blog/2025-09-12-ssh-session-env/ssh-session-env.mdx
  blog/2025-09-15-kubectl-exec/assets/bcm-arch.png
  blog/2025-09-15-kubectl-exec/assets/chaos-mesh-arch.png
  blog/2025-09-15-kubectl-exec/assets/cmd-flow.png
  blog/2025-09-15-kubectl-exec/from-chaosblade-to-kubectl-exec.mdx
  docusaurus.config.ts
  package-lock.json
  package.json
Labels: Review effort 2/5

#31 feat: enhance the site
  blog/tags.yml
  docusaurus.config.ts
  src/components/HomepageFeatures/index.tsx
  src/components/HomepageFeatures/styles.module.css
  static/img/docusaurus-social-card.jpg
  static/img/docusaurus.png
  static/img/favicon.ico
  static/img/logo.svg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
Labels: Review effort 2/5

#34 feat: add GItHub sponsor components to blogs
  blog/2025-05-09-bcm-engine/0-bcm-engine.mdx
  blog/2025-05-09-bcm-engine/1-open-source-project-selection.mdx
  blog/2025-05-09-bcm-engine/2-internal-adaption.mdx
  blog/2025-05-09-bcm-engine/3-bugfix.mdx
  blog/2025-05-09-bcm-engine/4-future.mdx
  blog/2025-09-11-service-startup-exp/startup-exp.mdx
  blog/2025-09-12-ssh-session-env/ssh-session-env.mdx
  blog/2025-09-15-kubectl-exec/from-chaosblade-to-kubectl-exec.mdx
  docusaurus.config.ts
  package-lock.json
  package.json
  src/components/SponsorIframe.tsx
  src/theme/MDXComponents.js
Labels: Review effort 2/5, Possible security concern
